### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by pedro-n-rocha** [ElDavoo/agevo#2]
https://github.com/ElDavoo/agevo/wiki/It:-Codice-sorgente

the TODO part ? put them here ???

**Comment by ElDavoo** [comment]
There are some people who are maintaining sources for this router. I asked their permission to upload them here.

**Comment by ElDavoo** [comment]
Unfortunately they are not complete, so they will not work, but I'm going
to upload them soon.

Il mer 21 feb 2018, 02:50 procha <notifications@github.com> ha scritto:

**Comment by pedro-n-rocha** [comment]
thanks 

apreciated
